const postDb = [
  {
    id: 1,
    createdOn: new Date(),
    createdBy: 1,
    type: 'red-flag',
    location: '6.5951139, 3.3429975',
    status: 'resolved',
    Images: ['image1.jpg', 'image2.jpg'],
    Videos: ['video1.mp4', 'video2.mp4'],
    comment: 'Extortion by the police',
  },
  {
    id: 2,
    createdOn: new Date(),
    createdBy: 3,
    type: 'red-flag',
    location: '6.5922139, 3.3427375',
    status: 'rejected',
    Images: [],
    Videos: [],
    comment: 'Lecturer harrasment',
  },
  {
    id: 3,
    createdOn: new Date(),
    createdBy: 2,
    type: 'red-flag',
    location: '6.5951139, 3.3408975',
    status: 'resolved',
    Images: ['image1.jpg', 'image2.jpg'],
    Videos: ['video1.mp4', 'video2.mp4'],
    comment: 'Bribery and extortion by the Police',
  },
  {
    id: 4,
    createdOn: new Date(),
    createdBy: 8,
    type: 'red-flag',
    location: '6.5955639, 3.3429775',
    status: 'under investigation',
    Images: ['image1.jpg', 'image2.jpg'],
    Videos: ['video1.mp4', 'video2.mp4'],
    comment: 'Rigging at the polling unit',
  },
  {
    id: 5,
    createdOn: new Date(),
    createdBy: 6,
    type: 'red-flag',
    location: '6.5977139, 3.3329975',
    status: 'resolved',
    Images: [],
    Videos: [],
    comment: 'Squandering of allocated money for contract',
  },
  {
    id: 6,
    createdOn: new Date(),
    createdBy: 5,
    type: 'red-flag',
    location: '6.5954769, 3.3675975',
    status: 'resolved',
    Images: ['image1.jpg', 'image2.jpg'],
    Videos: ['video1.mp4', 'video2.mp4'],
    comment: 'Siphoning of funds to foreign accounts',
  },
  {
    id: 7,
    createdOn: new Date(),
    createdBy: 7,
    type: 'red-flag',
    location: '6.5977220, 3.3329076',
    status: 'under investigation',
    Images: [],
    Videos: [],
    comment: 'Extortion at the airport',
  },
  {
    id: 8,
    createdOn: new Date(),
    createdBy: 4,
    type: 'red-flag',
    location: '6.5955639, 3.3429775',
    status: 'rejected',
    Images: [],
    Videos: [],
    comment: 'Stack of money locked inside a building',
  },
];

export default postDb;
